# Generated by Django 3.2.8 on 2021-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassmachine',
            name='model',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='qrCodeIdentifier',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
