# Generated by Django 3.2.8 on 2021-10-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211021_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassmachine',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grassmachine',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
