# Generated by Django 3.2.8 on 2021-10-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211021_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grassmachine',
            old_name='qrCodeIdentifier',
            new_name='qr_code_identifier',
        ),
    ]
