# Generated by Django 3.2.8 on 2021-11-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_grassmachine_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassmachine',
            name='description',
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='battery_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='cut_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='motor_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='rotation_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='serie_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='grassmachine',
            name='voltage',
            field=models.IntegerField(null=True),
        ),
    ]
